# Stage 1: Build using Maven and JDK 21
FROM maven:3.9.9-eclipse-temurin-21-alpine AS builder
WORKDIR /build
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2: Runtime using a lightweight JRE 21
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

# Copy the specific JAR generated by your pom.xml
COPY --from=builder /build/target/Restricted-Navigation-Bar-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]